### ISSUE TITLE
missing video on LSFB-iso

### ISSUE THREAD

**Issue by nikos-rvnt** [Jefidev/lsfb-dataset#14]
While, trying to download the LSFB dataset, as described [here](https://github.com/LSFB-Team/lsfb-dataset/blob/master/examples/download_example.ipynb), I got an error message 

"FileNotFoundError: 
                Could not download the desired file: videos/CLSFBI0307A_S008_B_652647_652959.mp4.
                Resource not found (https://lsfb.info.unamur.be/static/datasets/lsfb_v2/isol/videos/CLSFBI0307A_S008_B_652647_652959.mp4)"

and this error message stopped the downloading process, having downloaded only 115 isolated SL videos out of the 96184 (considering the instances.csv file).

**Comment by ppoitier** [comment]
Hello, we have identified the problem. We are currently working on it. As soon as it's fixed and the files are up to date on the server, we'll let you know! Sorry for the inconvenience.

**Comment by ppoitier** [comment]
The server problem should now be solved. You can now try downloading the dataset! Please let us know if it works, or if it doesn't.

**Comment by nikos-rvnt** [comment]
Things are better, the download process loads till 52%, but...

Videos for 120739 instances:  52%|████████████▉            | 62320/120739 [00:00<00:00, 168304.40files/s]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../lib/python3.9/site-packages/lsfb_dataset/download/downloader.py", line 224, in download
    self._download_files(
  File ".../lib/python3.9/site-packages/lsfb_dataset/download/downloader.py", line 201, in _download_files
    thread_map(
  File ".../lib/python3.9/site-packages/tqdm/contrib/concurrent.py", line 69, in thread_map
    return _executor_map(ThreadPoolExecutor, fn, *iterables, **tqdm_kwargs)
  File ".../lib/python3.9/site-packages/tqdm/contrib/concurrent.py", line 51, in _executor_map
    return list(tqdm_class(ex.map(fn, *iterables, chunksize=chunksize), **kwargs))
  File ".../lib/python3.9/site-packages/tqdm/std.py", line 1182, in __iter__
    for obj in iterable:
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 609, in result_iterator
    yield fs.pop().result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File ".../lib/python3.9/site-packages/lsfb_dataset/download/downloader.py", line 180, in _download_file
    raise FileNotFoundError(
FileNotFoundError: 
                Could not download the desired file: videos/CLSFBI4403A_S089_B_299833_300889.mp4.
                Wrong  HTTP status (500) for request (https://lsfb.info.unamur.be/static/datasets/lsfb_v2/isol/videos/CLSFBI4403A_S089_B_299833_300889.mp4).

**Comment by ppoitier** [comment]
Yes, unfortunately I've noticed that the server is down. I'll investigate and I'll get back to you as soon as possible. I'm really sorry about these technical issues!

**Comment by Jefidev** [comment]
Hello, 

To give some insight into what happened.

An incomplete data pre-processing pipelines caused the initial error. We added new annotated videos to the dataset and the landmarks were correctly uploaded on the dataset server but not the video.

The HTTP status 500 error is still being investigated. I was also downloading the dataset to test if everything was fine. Maybe it was too much for the little server we got.

**Comment by nikos-rvnt** [comment]
Thank you for your quick answer and for the time you spend to solve the problem. I appreciate it because I would like to use your dataset in my experiments.

**Comment by Jefidev** [comment]
Ok it seems that it was an error in an .htaccess file. Now you can retry to download.

**Comment by nikos-rvnt** [comment]
You should close the issue. I downloaded all videos.
